version: '3'
services:

  web:
    image: node:10
    command:  "npm run serve"
    working_dir: /app
    volumes:
      - ./:/app
      
    ports:
      - "8080:8080"
    networks:
      - base


networks:
  base:

volumes:
  db_data: